#!/usr/bin/env ruby

p 'Starting posts qualifier'

require 'bundler'

Bundler.require(:default, :qualifier)

require_relative 'lib/datadog'

Datadog.emit_event("Qualifying unprocessed posts",
                   msg_title: '[Craigslist Scraper] Qualifier started',
                   priority: 'low',
                   tags: %w{ craigslist_scraper qualify_posts }
                  )

Mail.defaults do
  delivery_method :smtp, { address: 'smtp.gmail.com',
                           port: 587,
                           authentication: 'plain',
                           enable_starttls_auto: true,
                           domain:    ENV['MAIL_DOMAIN'],
                           user_name: ENV['MAIL_USER'],
                           password:  ENV['MAIL_PASS']
                         }
end

pg = PG.connect(host:     ENV['DATABASE_HOST'],
                port:     ENV.fetch('DATABASE_PORT', 5432).to_i,
                dbname:   ENV['DATABASE_NAME'],
                user:     ENV['DATABASE_USER'],
                password: ENV['DATABASE_PASS']
               )

keywords = %w{ ios
               android
               ruby
               rails
               python
               javascript
               app
               web
               application
               api
               rest
               restful
               programmer
               automate
               automation
               unix
               linux
               shell
               script
             }

tsquery = keywords.join(' | ')

potential_leads = pg.exec_params(<<-SQL, [tsquery])
                                   WITH newly_processed AS (UPDATE posts SET processed = true WHERE NOT processed RETURNING *)
                                   SELECT p.id, p.url, p.title, p.body
                                   FROM newly_processed p,
                                        to_tsquery($1) query
                                   WHERE p.body_ts @@ query OR p.title_ts @@ query
                                   ORDER BY ts_rank(title_ts, query, 32) DESC, ts_rank(body_ts, query, 32) DESC
                                 SQL

formatted_data = potential_leads.map do |post|
  post_body = post['body'].to_s.sub(/^QR Code.*\n/, '').strip

  <<-HTML
    <p>
      <a href="#{post['url']}">#{post['title']}</a>
      <br />
      #{post_body.gsub(/\s+/, ' ').slice(0, 255)}#{post_body.length > 255 ? '...' : ''}
    </p>
  HTML
end

require 'csv'

csv_data = CSV.generate do |csv|
  csv << ['id', 'url', 'title', 'is_relevant', 'notes']
  potential_leads.each do |post|
    csv << [post['id'], post['url'], post['title'], nil, nil]
  end
end

today = Date.today

Mail.deliver do
  to 'anna@amdirent.com'
  cc 'chall@amdirent.com, crankin@amdirent.com'
  from 'help@amdirent.com'
  subject "Craigslist Lead Digest for #{today.strftime('%a, %-d %b %Y')}"

  html_part do
    content_type 'text/html; charset=UTF-8'
    body <<-HTML
           <h2>Daily Lead Digest</h2>
           <table>
             <tr>
               <th>Keywords used:</td>
               <td>#{keywords.join(', ')}</td>
             </tr>
           </table>
           <p>#{potential_leads.count} potential leads; Ordered by search rank, highest first.</p>
           <p style="max-width: 800px">
             #{formatted_data.join("\n")}
           </p>
         HTML
  end

  add_file filename: "digest.#{today.iso8601}.csv",
           mime_type: 'text/csv',
           content: csv_data
end

Datadog.emit_event("Posts processed and qualified",
                   msg_title: '[Craigslist Scraper] Qualifier finished',
                   alert_type: 'success',
                   tags: %w{ craigslist_scraper qualify_posts }
                  )

p 'Mail sent'
