#!/usr/bin/env ruby

require 'bundler'

Bundler.require(:default, :development)

cities = %w{ newyork
             boston
             raleigh
             charlotte
             miami
             jacksonville
             austin
             chicago
             minneapolis
             dallas
             losangeles
             sandiego
             sfbay
             seattle
             portland
             detroit
           }

today   = Date.today.iso8601
queue   = 'amdirent-craigslist-test-queue'
job_def = 'amdirent-craigslist-test:4'

cities.each do |city|
  url = "https://#{city}.craigslist.org"

  args = [ "--job-name #{city}-job-#{today}",
           "--job-queue #{queue}",
           "--job-definition #{job_def}",
           "--parameters site_url='#{url}'"
         ]

  `aws --region us-east-1 batch submit-job #{args.join(' ')}`
end
