#!/usr/bin/env ruby

require 'bundler'

Bundler.require(:default)

require_relative 'lib/scraper'

require 'uri'
require 'yaml'

Typhoeus::Config.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'

root = File.expand_path(File.dirname(__FILE__))
config = YAML.load_file(File.join(root, 'config.yml'))

pg = PG.connect(config['database'])
pg.prepare('update', 'UPDATE posts SET body = $2, body_ts = to_tsvector($2), contact_email = $3, contact_phone = $4 WHERE id = $1')
pg.prepare('delete', 'DELETE FROM posts WHERE id = $1')

posts_to_scrape = pg.exec('SELECT id, url FROM posts WHERE body IS NULL');
posts_to_scrape.each do |post|
  post_body, reply_email, reply_phone = Scraper.scrape(post['url'])

  if post_body.nil?
    p "No data for #{post['url']}"
    next
  end

  p "Storing info for #{post['url']}"

  pg.exec_prepared('update', [post['id'], post_body, reply_email, reply_phone])
end
