#!/usr/bin/env ruby

require 'bundler'

Bundler.require(:default)

require_relative 'lib/spider'

Typhoeus::Config.user_agent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'

require 'yaml'

root = File.expand_path(File.dirname(__FILE__))
config = YAML.load_file(File.join(root, 'config.yml'))

pg = PG.connect(config['database'])

city_urls = pg.exec('SELECT url FROM city_boards ORDER BY random()').map { |r| r['url'] }

results = {}

city_urls.each do |city_url|
  Spider.crawl(city_url) do |post_url, post_title, referer|
    results[post_url] = {
      title: post_title
    }
  end

  placeholder_int = 0
  placeholders = []
  values = []
  results.each do |(url, data)|
    placeholders << "($#{placeholder_int += 1},$#{placeholder_int += 1})"
    values += [url, data[:title]]
  end

  query = "INSERT INTO posts (url, title) VALUES #{placeholders.join(',')} ON CONFLICT DO NOTHING"

  pg.exec_params(query, values)
end
